[project]
name = "shotrope"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "google-auth>=2.43.0",
    "google-genai>=1.55.0",
    "python-dotenv>=1.2.1",
]
